# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import animalai_pb2 as animalai__pb2


class AiPlayerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ThinkAction = channel.unary_unary(
                '/animalai.AiPlayer/ThinkAction',
                request_serializer=animalai__pb2.BoardReq.SerializeToString,
                response_deserializer=animalai__pb2.ActionRep.FromString,
                )


class AiPlayerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ThinkAction(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiPlayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ThinkAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ThinkAction,
                    request_deserializer=animalai__pb2.BoardReq.FromString,
                    response_serializer=animalai__pb2.ActionRep.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'animalai.AiPlayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AiPlayer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ThinkAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/animalai.AiPlayer/ThinkAction',
            animalai__pb2.BoardReq.SerializeToString,
            animalai__pb2.ActionRep.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
