name: Web

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "aniweb/**"

defaults:
  run:
    working-directory: aniweb

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --verbose
      - run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy -- -D warnings

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install cargo-tarpaulin

      - run: cargo tarpaulin --ignore-tests --verbose --all-features --workspace --timeout 120 --out Xml

      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
